# Generated by Django 4.1.5 on 2023-01-27 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(verbose_name='balance')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='date time modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'user balance',
                'verbose_name_plural': 'user balances',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Charge'), (2, 'purchase'), (1, 'Transfer')], verbose_name='Transaction type')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
